version: '3.8'
services:
  app:
    build: .
    ports:
      - '7890:7890'
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo:27017/proxy-logs
      PORT: 7890
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: