version: '3'
services:
  app:
    build: .
    ports:
      - '3001:3001'
    restart: always
    environment:
      NODE_ENV: testing
      MONGODB_URI_PROXY: mongodb://172.17.0.1:27017/proxy-logs
      PORT: 3001
volumes:
  mongo-data: